name: Minimal install

on:
  pull_request:
    branches: [ develop, main, release/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Prepare on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update
        if: startswith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update

      - name: Restore build caches
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}

      - name: Install Metasystem
        env:
          TERM: linux
        run: |
          git submodule update --init --recursive
          cd scripts
          ./install_minimal_metasystem.sh

      - name: Run cxx tests
        run: |
          cd scripts
          ./build_ps.sh -t
          ./tests/run_cxx_ps_tests.sh
          ./run_cxx_ps.sh -t
